### ISSUE TITLE
Telegram bot no funciona

### ISSUE THREAD

**Issue by Nicolas-Melluso** [themarioga/CCLHBotPlusPlus#2]
Puedo ayudar directamente en la revisión y funcionalidad si se precisa

**Comment by themarioga** [comment]
Buenas, he creado una issue explicando mas o menos el error

https://github.com/themarioga/CCLHBot/issues/3

Estaré encantado de aceptar un pull request o cualquier tipo de aviso si consigues solucionar el error y volver a levantar el bot en mi VPS si vuelve a ser funcional.
